const REQUEST_BEGIN = 'REQUEST_BEGIN'
const REQUEST_SUCCESS= 'REQUEST_SUCCESS'
const REQUEST_FAILED = 'REQUEST_FAILED'

const RECEIVE_SCORE_LIST = 'RECEIVE_SCORE_LIST'
const UPDATE_SCORE_LIST = 'UPDATE_SCORE_LIST'
const CHANGE_SCORE_OPTIONS_YEAR = 'CHANGE_SCORE_OPTIONS_YEAR'
const CHANGE_SCORE_OPTIONS_TERM = 'CHANGE_SCORE_OPTIONS_TERM'
const FETCH_COURSE_TABLE = 'FETCH_COURSE_TABLE'
const FETCH_EMPTY_CLASSROOM = 'FETCH_EMPTY_CLASSROOM'

export {
  REQUEST_BEGIN,
  REQUEST_FAILED,
  REQUEST_SUCCESS,
  UPDATE_SCORE_LIST,
  RECEIVE_SCORE_LIST,
  CHANGE_SCORE_OPTIONS_TERM,
  CHANGE_SCORE_OPTIONS_YEAR,
  FETCH_COURSE_TABLE,
  FETCH_EMPTY_CLASSROOM
}
